### ISSUE TITLE
Main Jeopardy Page

### ISSUE THREAD

**Issue by antman1p** [isislab/CSAW-CTF-2017-Quals#1]
Do you happen to have the main, jeopardy page with the categories, points, hints, etc...?  Maybe the directory containing the html, css, and scripts that I can host locally for my team to practice?

**Comment by kallsyms** [comment]
We use [CTFd](https://github.com/CTFd/CTFd) if you want to setup your own instance, but the theme is private.

**Comment by antman1p** [comment]
Thank you!  How were you able to set dynamic keys?  For instance for the Crypto: AnotherXOR.
